Forgot result codes for run end, deal with 0 failed tests in statistics

diff --git a/pveruntests b/pveruntests
--- a/pveruntests
+++ b/pveruntests
@@ -19,6 +19,7 @@ runjob() {
 runend() {
    while test "${#running[*]}" -gt 0; do
       wait -p pid -n ${running[*]}
+      result+=( $? )
       for slot in ${!running[@]}; do
          test "${running[$slot]}" = "$pid" && break
       done
@@ -120,4 +121,5 @@ time=$(printf "%0.2f" $(echo "($end - $start) / 1000000000" | bc -l))
 tps=$(printf "%0.1f" $(echo "${#result[*]} / $time" | bc -l))
 echo "Ran ${#result[*]} tests in $time seconds ($tps tests per second)."
 fail=$(printf "%d\n" ${result[*]} | sort | uniq -c | sed "s/  //g" | grep " 1$" | cut -d ' ' -f 1)
+test "$fail" = "" && fail=0
 echo "$fail of ${#result[*]} tests failed ($(printf "%0.1f" $(echo "$fail / ${#result[*]} * 100" | bc -l))%)"
