createtemplate internal to pvete

diff --git a/pvete b/pvete
--- a/pvete
+++ b/pvete
@@ -7,6 +7,7 @@ usage() {
    echo
    echo "  -c <cfgfile>       Use specific config file"
    echo "  -d                 Dryrun, don't execute"
+   echo "  createtemplate     Create/overwrite template on server"
    echo "  deploy <drawing>   Deploy containers accoring to drawio drawing"
    echo "  list               Show deployed containers"
    echo "  enter <name>       Start shell on container"
@@ -45,9 +46,17 @@ findbridge() {
    echo "$bridge"
 }
 
+createtemplate() {
+   scriptloc=$(dirname $(realpath "$0"))
+   test -e "$scriptloc/_pvete-createtemplate" || { echo "Unable to find _pvete-createtemplate"; exit 1; }
+   scp -q "$scriptloc/_pvete-createtemplate" "$CTSERVER:/tmp/" || { echo "Unable to copy script"; exit 1; }
+   ssh "${CTSERVER}" "/tmp/_pvete-createtemplate $CTTEMPLATE"
+   ssh "${CTSERVER}" "rm -f /tmp/_pvete-createtemplate" || { echo "Unable to remove script"; exit 1; }
+}
+
 deploy() {
    scriptloc=$(dirname $(realpath "$0"))
-   test -e "$scriptloc/pve-testenv.sh" || { echo "Unable to find pve-testenv.sh"; exit 1; }
+   test -e "$scriptloc/_pve-testenv.sh" || { echo "Unable to find _pve-testenv.sh"; exit 1; }
 
    tmplstorage="$(ssh "${CTSERVER}" "pvesm status --content vztmpl | sed -n '2 s/ .*//p'")"
    test "$tmplstorage" = "" && { echo "Unable to find template storage"; exit 1; }
@@ -115,11 +124,10 @@ deploy() {
 	[Install]
 	WantedBy=multi-user.target
 	EOF
-      #cat pve-testenvproxy.service | sed "s#SHARED#$CTSHARED/proxy#; s#PROXY#$PROXY#" | ssh "${CTSERVER}" "cat - > /lib/systemd/system/pve-testenvproxy.service"
       ssh "$CTSERVER" "systemctl enable pve-testenvproxy.service > /dev/null; systemctl start pve-testenvproxy.service"
    fi
    test "$DRY" -eq 0 && ssh "$CTSERVER" "echo \"127.0.0.1 localhost\" > \"${CTSHARED}/hosts\""
-   test "$DRY" -eq 0 && scp -q "$scriptloc/pve-testenv.sh" "$CTSERVER:/${CTSHARED}/"
+   test "$DRY" -eq 0 && scp -q "$scriptloc/_pve-testenv.sh" "$CTSERVER:/${CTSHARED}/pve-testenv.sh"
    test "$DRY" -eq 0 && { ssh "$CTSERVER" "chown 100000:100000 \"${CTSHARED}/pve-testenv.sh\"; chmod 700 \"${CTSHARED}/pve-testenv.sh\"; rm -f \"${CTSHARED}/deployed\""; }
    
    declare -A ctcmds
@@ -195,6 +203,7 @@ done
 test "$cfgfound" -eq 0 && { echo "No configuration file found"; usage; }
 
 test "$1" = "deploy" && { shift; deploy "$@"; exit 0; }
+test "$1" = "createtemplate" && { shift; createtemplate; exit 0; }
 
 declare -A cts
 getcts
